sudo: required
services:
  - docker
env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - docker build -t quay.io/ssro/nmon .

script: echo "No test"

after_success:
  - export REPO=quay.io/ssro/nmon
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" && docker push $REPO
